

###

POST  http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
    "username": "Orcawy",
    "email": "orcawy@gmail.com",
    "password": "20201114"
}

###

POST  http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
    "username": "seif",
    "email": "seif@gmail.com",
    "password": "20200239"
}

###
POST  http://localhost:8080/signin HTTP/1.1
Content-Type: application/json

{
    "email": "orcawy@gmail.com",
    "password": "20201114"
}
###
POST  http://localhost:8080/signin HTTP/1.1
Content-Type: application/json

{
    "email": "seif@gmail.com",
    "password": "20200239"
}
###
POST  http://localhost:8080/admin/addsp HTTP/1.1
Content-Type: application/json

{
    "name": "Vodafone Cash",
    "serviceName": "Mobile recharge",
    "number" : "961093",
    "formComponentsNumber": "2",
    "formComponent0" : "0Mobile Number",
    "formComponent1" : "1Amount"
}
###
POST  http://localhost:8080/admin/addsp HTTP/1.1
Content-Type: application/json

{
    "name": "Magdy Yacoub",
    "serviceName": "Donations",
    "number" : "902",
    "formComponentsNumber": "3",
    "formComponent0" : "0Mobile Number",
    "formComponent1" : "1Amount",
    "formComponent2" : "0category"
}
###
POST  http://localhost:8080/admin/addsp HTTP/1.1
Content-Type: application/json

{
    "name": "Government",
    "serviceName": "Landline",
    "number" : "993",
    "formComponentsNumber": "2",
    "formComponent0" : "0Mobile Number",
    "formComponent1" : "1Amount"
}

###

POST  http://localhost:8080/walletrecharge HTTP/1.1
Content-Type: application/json

{
    "username": "Orcawy",
    "amount"  : "300"
}
###

POST  http://localhost:8080/walletrecharge HTTP/1.1
Content-Type: application/json

{
    "username": "seif",
    "amount"  : "200"
}

###
POST  http://localhost:8080/payservice HTTP/1.1
Content-Type: application/json

{
    "email": "seif@gmail.com",
    "password"  : "20200239",
    "totalcost" : "300",
    "spnumber" : "961093",
    "servicename" : "Mobile recharge",
    "paymentMethod" : "cash"
}

###
POST  http://localhost:8080/payservice HTTP/1.1
Content-Type: application/json

{
    "email": "seif@gmail.com",
    "password"  : "20200239",
    "totalcost" : "100",
    "spnumber" : "902",
    "servicename" : "Donations",
    "paymentMethod" : "wallet"
}

###
POST  http://localhost:8080/payservice HTTP/1.1
Content-Type: application/json

{
    "email": "orcawy@gmail.com",
    "password"  : "20201114",
    "totalcost" : "200.0",
    "spnumber" : "993",
    "servicename" : "Landline",
    "paymentMethod" : "Credit Card"
}

###
POST  http://localhost:8080/User/RequestRefund HTTP/1.1
Content-Type: application/json

{
    "email": "seif@gmail.com",
    "password": "20200239",
    "payid": "0"
    
}
###
POST  http://localhost:8080/User/RequestRefund HTTP/1.1
Content-Type: application/json

{
    "email": "orcawy@gmail.com",
    "password": "20201114",
    "payid": "1"
    
}

###
GET http://localhost:8080/admin/ShowUserPayment/seif HTTP/1.1

###
GET http://localhost:8080/admin/ShowUserRefundList/seif HTTP/1.1
###
GET http://localhost:8080/admin/ShowUserRefundList/Orcawy HTTP/1.1

###
GET http://localhost:8080/admin/ShowUserWallet/Orcawy HTTP/1.1

###
GET http://localhost:8080/admin/ShowUserWallet/seif HTTP/1.1

###
GET http://localhost:8080/search/Mobile HTTP/1.1

###
GET http://localhost:8080/admin/getRefundList HTTP/1.1


###
POST  http://localhost:8080/admin/acceptanceOfRefunds HTTP/1.1
Content-Type: application/json

{
    "payid": "0",
    "username": "Orcawy",
    "response":"accepted"
    
}
###
POST  http://localhost:8080/admin/acceptanceOfRefunds HTTP/1.1
Content-Type: application/json

{
    "payid": "0",
    "username": "seif",
    "response":"rejected"
    
}


###
POST  http://localhost:8080/admin/addDiscount HTTP/1.1
Content-Type: application/json

{
    "servicename": "Mobile recharge",
    "discountPercentage": 10
    
}
###

GET http://localhost:8080/user/checkDiscounts?serviceName=Mobile recharge HTTP/1.1
